In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_excel('./sources/tranzakciok.xlsx')
df.head()

c:\Users\feket\Desktop\Center\home-lab\finance-pipeline\venv\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Tranzakció dátuma,Könyvelés dátuma,Típus,Bejövő/Kimenő,Partner neve,Partner számlaszáma/azonosítója,Költési kategória,Közlemény,Számla név,Számla szám,Összeg,Pénznem
0,2026-01-01 07:36:00,2026-01-01,KAMATJÓVÁÍRÁS,Bejövő,KAMATJÓVÁÍRÁS,NaN,"Számlák, rezsi",51 SZOCHO alap: 51 SZOCHO összeg: 7 Kamatadó: 8,Bázis számla,1177340101379288,36,HUF
1,2026-01-01 07:36:00,2026-01-01,HAVI CSOMAGDÍJ,Kimenő,HAVI CSOMAGDÍJ,NaN,"Számlák, rezsi",NaN,Bázis számla,1177340101379288,-449,HUF
2,2026-01-02 13:07:57,2026-01-05,VÁSÁRLÁS KÁRTYÁVAL,Kimenő,SIMPLEP*JEGYMESTER.HU,NaN,Egyéb,2026.01.02 8938043657 SIMPLEP*JEGYMESTER.HU ...,Bázis számla,1177340101379288,-6600,HUF
3,2026-01-02 15:33:59,2026-01-05,VÁSÁRLÁS KÁRTYÁVAL,Kimenő,CBA ÉLELMISZER VII.,NaN,Bevásárlás,2026.01.02 8938043657 CBA ÉLELMISZER VII. ...,Bázis számla,1177340101379288,-4396,HUF
4,2026-01-03 17:51:44,2026-01-05,VÁSÁRLÁS KÁRTYÁVAL,Kimenő,HELOPAY*VILAG BORAI KI,NaN,Bevásárlás,2026.01.03 8938043657 HELOPAY*VILAG BORAI KISK...,Bázis számla,1177340101379288,-11213,HUF

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 12 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Tranzakció dátuma                79 non-null     str
 1   Könyvelés dátuma                 75 non-null     str
 2   Típus                            75 non-null     str
 3   Bejövő/Kimenő                    79 non-null     str
 4   Partner neve                     79 non-null     str
 5   Partner számlaszáma/azonosítója  3 non-null      float64
 6   Költési kategória                79 non-null     str
 7   Közlemény                        72 non-null     str
 8   Számla név                       79 non-null     str
 9   Számla szám                      79 non-null     int64
 10  Összeg                           79 non-null     int64
 11  Pénznem                          79 non-null     str
dtypes: float64(1), int64(2), str(9)
memory usage: 7.5 KB

In [ ]:
df[df["Partner számlaszáma/azonosítója"].notna()]

,Tranzakció dátuma,Könyvelés dátuma,Típus,Bejövő/Kimenő,Partner neve,Partner számlaszáma/azonosítója,Költési kategória,Közlemény,Számla név,Számla szám,Összeg,Pénznem
45,2026-01-19 22:11:25,2026-01-20,AZONNALI FIZETÉS BANKON BELÜL,Kimenő,Tóth Máté Gergely,1.173801e+15,Utalás,Fekete Gergő teája,Bázis számla,1177340101379288,-25230,HUF
46,2026-01-20 01:38:00,2026-01-20,ESETI MEGBÍZÁSOK KÖLTSÉGE,Kimenő,ESETI MEGBÍZÁSOK KÖLTSÉGE,1.173801e+15,Egyéb,NaN,Bázis számla,1177340101379288,-333,HUF
71,2026-01-30 07:48:00,2026-01-30,NAPKÖZBENI ÁTUTALÁS (CSOPORTOS),Bejövő,UNICREDIT BANK ZRT. IZV SUSPENSE,1.091800e+23,Nem kategorizált,Munkabér utalás,Bázis számla,1177340101379288,514890,HUF

: